version: 2.1
parameters:
  gradle-args:
    type: string
    default: "-Prevision=<< pipeline.git.revision >>"
jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run tests
          command: ./gradlew check << pipeline.parameters.gradle-args >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  build:
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Publish Docker image with Jib
          command: ./gradlew jib << pipeline.parameters.gradle-args >>
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
